"""Endgame helpers for bearoff tables generated by the Rust engine.

Only the indexing utilities remain in Python; generation and lookup live in
``rust/bearoff`` (exposed via Python bindings). Tables store the gnubg-aligned
ordering and 7 float32 values per entry:
- win, gammon_win, loss, gammon_loss
- cubeful equities: centered, owner, opponent
"""

from .indexing import (
    position_to_index,
    index_to_position,
    total_positions,
    TOTAL_ONE_SIDED_POSITIONS,
)

__all__ = [
    'position_to_index',
    'index_to_position',
    'total_positions',
    'TOTAL_ONE_SIDED_POSITIONS',
]
